### ISSUE TITLE
Background color is missing from CSS

### ISSUE THREAD

**Issue by tastytea** [xenodium/xenodium.github.io#2]
The website looks like this for me:
![screenshot_2020-03-21T20-51-02](https://user-images.githubusercontent.com/3681516/77235439-ee54aa00-6bb5-11ea-99b9-fda6eb45a92b.png)
![screenshot_2020-03-21T20-54-07](https://user-images.githubusercontent.com/3681516/77235462-24922980-6bb6-11ea-9fc6-88f58dde162c.png)

After adding `background-color: white;` to `body {}`, it looks like this:
![screenshot_2020-03-21T20-51-17](https://user-images.githubusercontent.com/3681516/77235445-00cee380-6bb6-11ea-80bf-00f53cca0c6f.png)

To reproduce, configure your browser to use white text on black background as fallback ([Firefox](https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use#w_change-font-color)).

**Comment by xenodium** [comment]
Thanks for this. Tried a few things from the docs pointed to, but didn't manage to reproduce. Mind adding a screenshot of your Firefox font/color settings?

**Comment by tastytea** [comment]
I can't reproduce it anymore. Maybe it was a bug in Firefox.

**Comment by xenodium** [comment]
Thanks for trying it out.
